//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.Report.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TT.Report.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Section.
        /// </summary>
        public static string section_part_general {
            get {
                return ResourceManager.GetString("section_part_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Section.
        /// </summary>
        public static string section_part_player {
            get {
                return ResourceManager.GetString("section_part_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement.
        /// </summary>
        public static string section_placement {
            get {
                return ResourceManager.GetString("section_placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side.
        /// </summary>
        public static string section_side {
            get {
                return ResourceManager.GetString("section_side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin.
        /// </summary>
        public static string section_spin {
            get {
                return ResourceManager.GetString("section_spin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string section_spin_down {
            get {
                return ResourceManager.GetString("section_spin_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string section_spin_hidden {
            get {
                return ResourceManager.GetString("section_spin_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost.
        /// </summary>
        public static string section_spin_lost {
            get {
                return ResourceManager.GetString("section_spin_lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string section_spin_no {
            get {
                return ResourceManager.GetString("section_spin_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string section_spin_up {
            get {
                return ResourceManager.GetString("section_spin_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won.
        /// </summary>
        public static string section_spin_won {
            get {
                return ResourceManager.GetString("section_spin_won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All strokes.
        /// </summary>
        public static string section_stroke_name_all {
            get {
                return ResourceManager.GetString("section_stroke_name_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth stroke.
        /// </summary>
        public static string section_stroke_name_fourth {
            get {
                return ResourceManager.GetString("section_stroke_name_fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last stroke.
        /// </summary>
        public static string section_stroke_name_last {
            get {
                return ResourceManager.GetString("section_stroke_name_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return stroke.
        /// </summary>
        public static string section_stroke_name_return {
            get {
                return ResourceManager.GetString("section_stroke_name_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service stroke.
        /// </summary>
        public static string section_stroke_name_service {
            get {
                return ResourceManager.GetString("section_stroke_name_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third stroke.
        /// </summary>
        public static string section_stroke_name_third {
            get {
                return ResourceManager.GetString("section_stroke_name_third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string section_table {
            get {
                return ResourceManager.GetString("section_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique.
        /// </summary>
        public static string section_technique {
            get {
                return ResourceManager.GetString("section_technique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sets.
        /// </summary>
        public static string sets_all {
            get {
                return ResourceManager.GetString("sets_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string sets_one {
            get {
                return ResourceManager.GetString("sets_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net/Out.
        /// </summary>
        public static string table_netout_label {
            get {
                return ResourceManager.GetString("table_netout_label", resourceCulture);
            }
        }
    }
}
