//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.Report.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TT.Report.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backhand: ähnelt.
        /// </summary>
        public static string legend_backhand_title {
            get {
                return ResourceManager.GetString("legend_backhand_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Banana / Flip ähnelt.
        /// </summary>
        public static string legend_banana_flip_title {
            get {
                return ResourceManager.GetString("legend_banana_flip_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block / Counter ähnelt.
        /// </summary>
        public static string legend_block_counter_title {
            get {
                return ResourceManager.GetString("legend_block_counter_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chop ähnelt.
        /// </summary>
        public static string legend_chop_title {
            get {
                return ResourceManager.GetString("legend_chop_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forehand: ähnelt.
        /// </summary>
        public static string legend_forehand_title {
            get {
                return ResourceManager.GetString("legend_forehand_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intercept ähnelt.
        /// </summary>
        public static string legend_lineexplanation_intercept_title {
            get {
                return ResourceManager.GetString("legend_lineexplanation_intercept_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Point of contact → Placement ähnelt.
        /// </summary>
        public static string legend_lineexplanation_poc_pl_title {
            get {
                return ResourceManager.GetString("legend_lineexplanation_poc_pl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lob ähnelt.
        /// </summary>
        public static string legend_lob_title {
            get {
                return ResourceManager.GetString("legend_lob_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Misc ähnelt.
        /// </summary>
        public static string legend_misc_title {
            get {
                return ResourceManager.GetString("legend_misc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Push ähnelt.
        /// </summary>
        public static string legend_push_title {
            get {
                return ResourceManager.GetString("legend_push_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table legend ähnelt.
        /// </summary>
        public static string legend_section_header {
            get {
                return ResourceManager.GetString("legend_section_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service (with spin) ähnelt.
        /// </summary>
        public static string legend_service_with_spin_title {
            get {
                return ResourceManager.GetString("legend_service_with_spin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service (without spin) ähnelt.
        /// </summary>
        public static string legend_service_without_spin_title {
            get {
                return ResourceManager.GetString("legend_service_without_spin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smash ähnelt.
        /// </summary>
        public static string legend_smash_title {
            get {
                return ResourceManager.GetString("legend_smash_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Topspin ähnelt.
        /// </summary>
        public static string legend_topspin_title {
            get {
                return ResourceManager.GetString("legend_topspin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die APPENDIX ähnelt.
        /// </summary>
        public static string part_appendix {
            get {
                return ResourceManager.GetString("part_appendix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E ähnelt.
        /// </summary>
        public static string placement_error_short {
            get {
                return ResourceManager.GetString("placement_error_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die h ähnelt.
        /// </summary>
        public static string placement_halflong_short {
            get {
                return ResourceManager.GetString("placement_halflong_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die l ähnelt.
        /// </summary>
        public static string placement_long_short {
            get {
                return ResourceManager.GetString("placement_long_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die s ähnelt.
        /// </summary>
        public static string placement_short_short {
            get {
                return ResourceManager.GetString("placement_short_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category ähnelt.
        /// </summary>
        public static string report_header_default_category {
            get {
                return ResourceManager.GetString("report_header_default_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Class ähnelt.
        /// </summary>
        public static string report_header_default_disabilityclass {
            get {
                return ResourceManager.GetString("report_header_default_disabilityclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Round ähnelt.
        /// </summary>
        public static string report_header_default_round {
            get {
                return ResourceManager.GetString("report_header_default_round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tournament ähnelt.
        /// </summary>
        public static string report_header_default_tournament {
            get {
                return ResourceManager.GetString("report_header_default_tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table Tennis Performance Report ähnelt.
        /// </summary>
        public static string report_header_headline {
            get {
                return ResourceManager.GetString("report_header_headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table Tennis Performance Report ähnelt.
        /// </summary>
        public static string report_title {
            get {
                return ResourceManager.GetString("report_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comp. Perf. ähnelt.
        /// </summary>
        public static string section_basicinfo_compref {
            get {
                return ResourceManager.GetString("section_basicinfo_compref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player ähnelt.
        /// </summary>
        public static string section_basicinfo_player {
            get {
                return ResourceManager.GetString("section_basicinfo_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ranking ähnelt.
        /// </summary>
        public static string section_basicinfo_ranking {
            get {
                return ResourceManager.GetString("section_basicinfo_ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result ähnelt.
        /// </summary>
        public static string section_basicinfo_result {
            get {
                return ResourceManager.GetString("section_basicinfo_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service ähnelt.
        /// </summary>
        public static string section_basicinfo_service {
            get {
                return ResourceManager.GetString("section_basicinfo_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freq. ähnelt.
        /// </summary>
        public static string section_basicinfo_service_freq {
            get {
                return ResourceManager.GetString("section_basicinfo_service_freq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Win. Prob. ähnelt.
        /// </summary>
        public static string section_basicinfo_service_winprob {
            get {
                return ResourceManager.GetString("section_basicinfo_service_winprob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Basic Information ähnelt.
        /// </summary>
        public static string section_basicinfo_title {
            get {
                return ResourceManager.GetString("section_basicinfo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total Points ähnelt.
        /// </summary>
        public static string section_basicinfo_totalpoints {
            get {
                return ResourceManager.GetString("section_basicinfo_totalpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Win. Prob. ähnelt.
        /// </summary>
        public static string section_basicinfo_winprob {
            get {
                return ResourceManager.GetString("section_basicinfo_winprob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You haven&apos;t selected any statistics for any strokes, thus the section for player {0} is empty. ähnelt.
        /// </summary>
        public static string section_empty_warning {
            get {
                return ResourceManager.GetString("section_empty_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die By serving player ähnelt.
        /// </summary>
        public static string section_matchdynamics_byplayer {
            get {
                return ResourceManager.GetString("section_matchdynamics_byplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overall ähnelt.
        /// </summary>
        public static string section_matchdynamics_overall {
            get {
                return ResourceManager.GetString("section_matchdynamics_overall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Match dynamics ähnelt.
        /// </summary>
        public static string section_matchdynamics_title {
            get {
                return ResourceManager.GetString("section_matchdynamics_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General Section ähnelt.
        /// </summary>
        public static string section_part_general {
            get {
                return ResourceManager.GetString("section_part_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player Section ähnelt.
        /// </summary>
        public static string section_part_player {
            get {
                return ResourceManager.GetString("section_part_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Placement ähnelt.
        /// </summary>
        public static string section_placement {
            get {
                return ResourceManager.GetString("section_placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mean ähnelt.
        /// </summary>
        public static string section_rallylength_avg_mean {
            get {
                return ResourceManager.GetString("section_rallylength_avg_mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Median ähnelt.
        /// </summary>
        public static string section_rallylength_avg_median {
            get {
                return ResourceManager.GetString("section_rallylength_avg_median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service ähnelt.
        /// </summary>
        public static string section_rallylength_avg_service {
            get {
                return ResourceManager.GetString("section_rallylength_avg_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Average ähnelt.
        /// </summary>
        public static string section_rallylength_avg_title {
            get {
                return ResourceManager.GetString("section_rallylength_avg_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total lengths ähnelt.
        /// </summary>
        public static string section_rallylength_avg_totallengths {
            get {
                return ResourceManager.GetString("section_rallylength_avg_totallengths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Winner ähnelt.
        /// </summary>
        public static string section_rallylength_avg_winner {
            get {
                return ResourceManager.GetString("section_rallylength_avg_winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected ähnelt.
        /// </summary>
        public static string section_rallylength_dist_expected {
            get {
                return ResourceManager.GetString("section_rallylength_dist_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Observed ähnelt.
        /// </summary>
        public static string section_rallylength_dist_observed {
            get {
                return ResourceManager.GetString("section_rallylength_dist_observed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #Rallies ähnelt.
        /// </summary>
        public static string section_rallylength_dist_ralliescount {
            get {
                return ResourceManager.GetString("section_rallylength_dist_ralliescount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rally length ähnelt.
        /// </summary>
        public static string section_rallylength_dist_rallylength {
            get {
                return ResourceManager.GetString("section_rallylength_dist_rallylength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distribution ähnelt.
        /// </summary>
        public static string section_rallylength_dist_title {
            get {
                return ResourceManager.GetString("section_rallylength_dist_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rally Length ähnelt.
        /// </summary>
        public static string section_rallylength_title {
            get {
                return ResourceManager.GetString("section_rallylength_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoring process ähnelt.
        /// </summary>
        public static string section_scoringprocess_title {
            get {
                return ResourceManager.GetString("section_scoringprocess_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Side ähnelt.
        /// </summary>
        public static string section_side {
            get {
                return ResourceManager.GetString("section_side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Side (Steparound) ähnelt.
        /// </summary>
        public static string section_side_steparound {
            get {
                return ResourceManager.GetString("section_side_steparound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spin ähnelt.
        /// </summary>
        public static string section_spin {
            get {
                return ResourceManager.GetString("section_spin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Down ähnelt.
        /// </summary>
        public static string section_spin_down {
            get {
                return ResourceManager.GetString("section_spin_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hidden ähnelt.
        /// </summary>
        public static string section_spin_hidden {
            get {
                return ResourceManager.GetString("section_spin_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string section_spin_no {
            get {
                return ResourceManager.GetString("section_spin_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Up ähnelt.
        /// </summary>
        public static string section_spin_up {
            get {
                return ResourceManager.GetString("section_spin_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lost ähnelt.
        /// </summary>
        public static string section_stroke_lost {
            get {
                return ResourceManager.GetString("section_stroke_lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All strokes ähnelt.
        /// </summary>
        public static string section_stroke_name_all {
            get {
                return ResourceManager.GetString("section_stroke_name_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fourth stroke ähnelt.
        /// </summary>
        public static string section_stroke_name_fourth {
            get {
                return ResourceManager.GetString("section_stroke_name_fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last stroke ähnelt.
        /// </summary>
        public static string section_stroke_name_last {
            get {
                return ResourceManager.GetString("section_stroke_name_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Return stroke ähnelt.
        /// </summary>
        public static string section_stroke_name_return {
            get {
                return ResourceManager.GetString("section_stroke_name_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service stroke ähnelt.
        /// </summary>
        public static string section_stroke_name_service {
            get {
                return ResourceManager.GetString("section_stroke_name_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Third stroke ähnelt.
        /// </summary>
        public static string section_stroke_name_third {
            get {
                return ResourceManager.GetString("section_stroke_name_third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Won ähnelt.
        /// </summary>
        public static string section_stroke_won {
            get {
                return ResourceManager.GetString("section_stroke_won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stroke number ähnelt.
        /// </summary>
        public static string section_strokenumber {
            get {
                return ResourceManager.GetString("section_strokenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table ähnelt.
        /// </summary>
        public static string section_table {
            get {
                return ResourceManager.GetString("section_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string section_techefficiency_error {
            get {
                return ResourceManager.GetString("section_techefficiency_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Technical efficiency ähnelt.
        /// </summary>
        public static string section_techefficiency_title {
            get {
                return ResourceManager.GetString("section_techefficiency_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Technique ähnelt.
        /// </summary>
        public static string section_technique {
            get {
                return ResourceManager.GetString("section_technique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Banana ähnelt.
        /// </summary>
        public static string section_technique_banana {
            get {
                return ResourceManager.GetString("section_technique_banana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block ähnelt.
        /// </summary>
        public static string section_technique_block {
            get {
                return ResourceManager.GetString("section_technique_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block
        ///(diagonal) ähnelt.
        /// </summary>
        public static string section_technique_block_diag {
            get {
                return ResourceManager.GetString("section_technique_block_diag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block
        ///(Middle) ähnelt.
        /// </summary>
        public static string section_technique_block_middle {
            get {
                return ResourceManager.GetString("section_technique_block_middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block
        ///(parallel) ähnelt.
        /// </summary>
        public static string section_technique_block_parallel {
            get {
                return ResourceManager.GetString("section_technique_block_parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BlockChop ähnelt.
        /// </summary>
        public static string section_technique_blockchop {
            get {
                return ResourceManager.GetString("section_technique_blockchop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BlockTempo ähnelt.
        /// </summary>
        public static string section_technique_blocktempo {
            get {
                return ResourceManager.GetString("section_technique_blocktempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chop ähnelt.
        /// </summary>
        public static string section_technique_chop {
            get {
                return ResourceManager.GetString("section_technique_chop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counter ähnelt.
        /// </summary>
        public static string section_technique_counter {
            get {
                return ResourceManager.GetString("section_technique_counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flip ähnelt.
        /// </summary>
        public static string section_technique_flip {
            get {
                return ResourceManager.GetString("section_technique_flip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lob ähnelt.
        /// </summary>
        public static string section_technique_lob {
            get {
                return ResourceManager.GetString("section_technique_lob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Miscellaneous ähnelt.
        /// </summary>
        public static string section_technique_miscellaneous {
            get {
                return ResourceManager.GetString("section_technique_miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N/A ähnelt.
        /// </summary>
        public static string section_technique_na {
            get {
                return ResourceManager.GetString("section_technique_na", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Push ähnelt.
        /// </summary>
        public static string section_technique_push {
            get {
                return ResourceManager.GetString("section_technique_push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Push
        ///(half-long) ähnelt.
        /// </summary>
        public static string section_technique_push_halflong {
            get {
                return ResourceManager.GetString("section_technique_push_halflong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Push
        ///(long) ähnelt.
        /// </summary>
        public static string section_technique_push_long {
            get {
                return ResourceManager.GetString("section_technique_push_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Push
        ///(short) ähnelt.
        /// </summary>
        public static string section_technique_push_short {
            get {
                return ResourceManager.GetString("section_technique_push_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PushAggressive ähnelt.
        /// </summary>
        public static string section_technique_pushaggressive {
            get {
                return ResourceManager.GetString("section_technique_pushaggressive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smash ähnelt.
        /// </summary>
        public static string section_technique_smash {
            get {
                return ResourceManager.GetString("section_technique_smash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special ähnelt.
        /// </summary>
        public static string section_technique_special {
            get {
                return ResourceManager.GetString("section_technique_special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Topspin ähnelt.
        /// </summary>
        public static string section_technique_topspin {
            get {
                return ResourceManager.GetString("section_technique_topspin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Topspin
        ///(diagonal) ähnelt.
        /// </summary>
        public static string section_technique_topspin_diag {
            get {
                return ResourceManager.GetString("section_technique_topspin_diag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Topspin
        ///(Middle) ähnelt.
        /// </summary>
        public static string section_technique_topspin_middle {
            get {
                return ResourceManager.GetString("section_technique_topspin_middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Topspin
        ///(parallel) ähnelt.
        /// </summary>
        public static string section_technique_topspin_parallel {
            get {
                return ResourceManager.GetString("section_technique_topspin_parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TopspinSpin ähnelt.
        /// </summary>
        public static string section_technique_topspinspin {
            get {
                return ResourceManager.GetString("section_technique_topspinspin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TopspinTempo ähnelt.
        /// </summary>
        public static string section_technique_topspintempo {
            get {
                return ResourceManager.GetString("section_technique_topspintempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Absolute number of transitions ähnelt.
        /// </summary>
        public static string section_transitionmatrix_abs_title {
            get {
                return ResourceManager.GetString("section_transitionmatrix_abs_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transition probabilities ähnelt.
        /// </summary>
        public static string section_transitionmatrix_prob_title {
            get {
                return ResourceManager.GetString("section_transitionmatrix_prob_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transition matrix ähnelt.
        /// </summary>
        public static string section_transitionmatrix_title {
            get {
                return ResourceManager.GetString("section_transitionmatrix_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All sets ähnelt.
        /// </summary>
        public static string sets_all {
            get {
                return ResourceManager.GetString("sets_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crunch time ähnelt.
        /// </summary>
        public static string sets_crunchtime {
            get {
                return ResourceManager.GetString("sets_crunchtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sets ähnelt.
        /// </summary>
        public static string sets_multiple {
            get {
                return ResourceManager.GetString("sets_multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set ähnelt.
        /// </summary>
        public static string sets_one {
            get {
                return ResourceManager.GetString("sets_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backhand ähnelt.
        /// </summary>
        public static string side_backhand {
            get {
                return ResourceManager.GetString("side_backhand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BH ähnelt.
        /// </summary>
        public static string side_backhand_short {
            get {
                return ResourceManager.GetString("side_backhand_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backhand (Steparound) ähnelt.
        /// </summary>
        public static string side_backhand_steparound {
            get {
                return ResourceManager.GetString("side_backhand_steparound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BH (SA) ähnelt.
        /// </summary>
        public static string side_backhand_steparound_short {
            get {
                return ResourceManager.GetString("side_backhand_steparound_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forehand ähnelt.
        /// </summary>
        public static string side_forehand {
            get {
                return ResourceManager.GetString("side_forehand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FH ähnelt.
        /// </summary>
        public static string side_forehand_short {
            get {
                return ResourceManager.GetString("side_forehand_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forehand (Steparound) ähnelt.
        /// </summary>
        public static string side_forehand_steparound {
            get {
                return ResourceManager.GetString("side_forehand_steparound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FH (SA) ähnelt.
        /// </summary>
        public static string side_forehand_steparound_short {
            get {
                return ResourceManager.GetString("side_forehand_steparound_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N/A ähnelt.
        /// </summary>
        public static string stat_not_analysed {
            get {
                return ResourceManager.GetString("stat_not_analysed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Net/Out ähnelt.
        /// </summary>
        public static string table_netout_label {
            get {
                return ResourceManager.GetString("table_netout_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blk ähnelt.
        /// </summary>
        public static string technique_block_short {
            get {
                return ResourceManager.GetString("technique_block_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chp ähnelt.
        /// </summary>
        public static string technique_chop_short {
            get {
                return ResourceManager.GetString("technique_chop_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cntr ähnelt.
        /// </summary>
        public static string technique_counter_short {
            get {
                return ResourceManager.GetString("technique_counter_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flp ähnelt.
        /// </summary>
        public static string technique_flip_short {
            get {
                return ResourceManager.GetString("technique_flip_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die T ähnelt.
        /// </summary>
        public static string technique_label_short {
            get {
                return ResourceManager.GetString("technique_label_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lb ähnelt.
        /// </summary>
        public static string technique_lob_short {
            get {
                return ResourceManager.GetString("technique_lob_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Misc ähnelt.
        /// </summary>
        public static string technique_miscellaneous_short {
            get {
                return ResourceManager.GetString("technique_miscellaneous_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pendulum ähnelt.
        /// </summary>
        public static string technique_pendulum {
            get {
                return ResourceManager.GetString("technique_pendulum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Psh ähnelt.
        /// </summary>
        public static string technique_push_short {
            get {
                return ResourceManager.GetString("technique_push_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reverse ähnelt.
        /// </summary>
        public static string technique_reverse {
            get {
                return ResourceManager.GetString("technique_reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sm ähnelt.
        /// </summary>
        public static string technique_smash_short {
            get {
                return ResourceManager.GetString("technique_smash_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special ähnelt.
        /// </summary>
        public static string technique_special {
            get {
                return ResourceManager.GetString("technique_special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spcl ähnelt.
        /// </summary>
        public static string technique_special_short {
            get {
                return ResourceManager.GetString("technique_special_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tomahawk ähnelt.
        /// </summary>
        public static string technique_tomahawk {
            get {
                return ResourceManager.GetString("technique_tomahawk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TS ähnelt.
        /// </summary>
        public static string technique_topspin_short {
            get {
                return ResourceManager.GetString("technique_topspin_short", resourceCulture);
            }
        }
    }
}
