//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.Report.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TT.Report.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string placement_error_short {
            get {
                return ResourceManager.GetString("placement_error_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string placement_halflong_short {
            get {
                return ResourceManager.GetString("placement_halflong_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l.
        /// </summary>
        public static string placement_long_short {
            get {
                return ResourceManager.GetString("placement_long_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string placement_short_short {
            get {
                return ResourceManager.GetString("placement_short_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Tennis Performance Report.
        /// </summary>
        public static string report_header_headline {
            get {
                return ResourceManager.GetString("report_header_headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Tennis Performance Report.
        /// </summary>
        public static string report_title {
            get {
                return ResourceManager.GetString("report_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comp. Perf..
        /// </summary>
        public static string section_basicinfo_compref {
            get {
                return ResourceManager.GetString("section_basicinfo_compref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string section_basicinfo_player {
            get {
                return ResourceManager.GetString("section_basicinfo_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string section_basicinfo_ranking {
            get {
                return ResourceManager.GetString("section_basicinfo_ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string section_basicinfo_result {
            get {
                return ResourceManager.GetString("section_basicinfo_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string section_basicinfo_service {
            get {
                return ResourceManager.GetString("section_basicinfo_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freq..
        /// </summary>
        public static string section_basicinfo_service_freq {
            get {
                return ResourceManager.GetString("section_basicinfo_service_freq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win. Prob..
        /// </summary>
        public static string section_basicinfo_service_winprob {
            get {
                return ResourceManager.GetString("section_basicinfo_service_winprob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string section_basicinfo_title {
            get {
                return ResourceManager.GetString("section_basicinfo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Points.
        /// </summary>
        public static string section_basicinfo_totalpoints {
            get {
                return ResourceManager.GetString("section_basicinfo_totalpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win. Prob..
        /// </summary>
        public static string section_basicinfo_winprob {
            get {
                return ResourceManager.GetString("section_basicinfo_winprob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By serving player.
        /// </summary>
        public static string section_matchdynamics_byplayer {
            get {
                return ResourceManager.GetString("section_matchdynamics_byplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall.
        /// </summary>
        public static string section_matchdynamics_overall {
            get {
                return ResourceManager.GetString("section_matchdynamics_overall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match dynamics.
        /// </summary>
        public static string section_matchdynamics_title {
            get {
                return ResourceManager.GetString("section_matchdynamics_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Section.
        /// </summary>
        public static string section_part_general {
            get {
                return ResourceManager.GetString("section_part_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Section.
        /// </summary>
        public static string section_part_player {
            get {
                return ResourceManager.GetString("section_part_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement.
        /// </summary>
        public static string section_placement {
            get {
                return ResourceManager.GetString("section_placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean.
        /// </summary>
        public static string section_rallylength_avg_mean {
            get {
                return ResourceManager.GetString("section_rallylength_avg_mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        public static string section_rallylength_avg_median {
            get {
                return ResourceManager.GetString("section_rallylength_avg_median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string section_rallylength_avg_service {
            get {
                return ResourceManager.GetString("section_rallylength_avg_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string section_rallylength_avg_title {
            get {
                return ResourceManager.GetString("section_rallylength_avg_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total lengths.
        /// </summary>
        public static string section_rallylength_avg_totallengths {
            get {
                return ResourceManager.GetString("section_rallylength_avg_totallengths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        public static string section_rallylength_avg_winner {
            get {
                return ResourceManager.GetString("section_rallylength_avg_winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected.
        /// </summary>
        public static string section_rallylength_dist_expected {
            get {
                return ResourceManager.GetString("section_rallylength_dist_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observed.
        /// </summary>
        public static string section_rallylength_dist_observed {
            get {
                return ResourceManager.GetString("section_rallylength_dist_observed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Rallies.
        /// </summary>
        public static string section_rallylength_dist_ralliescount {
            get {
                return ResourceManager.GetString("section_rallylength_dist_ralliescount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rally length.
        /// </summary>
        public static string section_rallylength_dist_rallylength {
            get {
                return ResourceManager.GetString("section_rallylength_dist_rallylength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution.
        /// </summary>
        public static string section_rallylength_dist_title {
            get {
                return ResourceManager.GetString("section_rallylength_dist_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rally Length.
        /// </summary>
        public static string section_rallylength_title {
            get {
                return ResourceManager.GetString("section_rallylength_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring process.
        /// </summary>
        public static string section_scoringprocess_title {
            get {
                return ResourceManager.GetString("section_scoringprocess_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side.
        /// </summary>
        public static string section_side {
            get {
                return ResourceManager.GetString("section_side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side (Steparound).
        /// </summary>
        public static string section_side_steparound {
            get {
                return ResourceManager.GetString("section_side_steparound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin.
        /// </summary>
        public static string section_spin {
            get {
                return ResourceManager.GetString("section_spin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string section_spin_down {
            get {
                return ResourceManager.GetString("section_spin_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string section_spin_hidden {
            get {
                return ResourceManager.GetString("section_spin_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string section_spin_no {
            get {
                return ResourceManager.GetString("section_spin_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string section_spin_up {
            get {
                return ResourceManager.GetString("section_spin_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost.
        /// </summary>
        public static string section_stroke_lost {
            get {
                return ResourceManager.GetString("section_stroke_lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All strokes.
        /// </summary>
        public static string section_stroke_name_all {
            get {
                return ResourceManager.GetString("section_stroke_name_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth stroke.
        /// </summary>
        public static string section_stroke_name_fourth {
            get {
                return ResourceManager.GetString("section_stroke_name_fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last stroke.
        /// </summary>
        public static string section_stroke_name_last {
            get {
                return ResourceManager.GetString("section_stroke_name_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return stroke.
        /// </summary>
        public static string section_stroke_name_return {
            get {
                return ResourceManager.GetString("section_stroke_name_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service stroke.
        /// </summary>
        public static string section_stroke_name_service {
            get {
                return ResourceManager.GetString("section_stroke_name_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third stroke.
        /// </summary>
        public static string section_stroke_name_third {
            get {
                return ResourceManager.GetString("section_stroke_name_third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won.
        /// </summary>
        public static string section_stroke_won {
            get {
                return ResourceManager.GetString("section_stroke_won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke number.
        /// </summary>
        public static string section_strokenumber {
            get {
                return ResourceManager.GetString("section_strokenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string section_table {
            get {
                return ResourceManager.GetString("section_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string section_techefficiency_error {
            get {
                return ResourceManager.GetString("section_techefficiency_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical efficiency.
        /// </summary>
        public static string section_techefficiency_title {
            get {
                return ResourceManager.GetString("section_techefficiency_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique.
        /// </summary>
        public static string section_technique {
            get {
                return ResourceManager.GetString("section_technique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banana.
        /// </summary>
        public static string section_technique_banana {
            get {
                return ResourceManager.GetString("section_technique_banana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string section_technique_block {
            get {
                return ResourceManager.GetString("section_technique_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block
        ///(diagonal).
        /// </summary>
        public static string section_technique_block_diag {
            get {
                return ResourceManager.GetString("section_technique_block_diag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block
        ///(Middle).
        /// </summary>
        public static string section_technique_block_middle {
            get {
                return ResourceManager.GetString("section_technique_block_middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block
        ///(parallel).
        /// </summary>
        public static string section_technique_block_parallel {
            get {
                return ResourceManager.GetString("section_technique_block_parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockChop.
        /// </summary>
        public static string section_technique_blockchop {
            get {
                return ResourceManager.GetString("section_technique_blockchop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockTempo.
        /// </summary>
        public static string section_technique_blocktempo {
            get {
                return ResourceManager.GetString("section_technique_blocktempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chop.
        /// </summary>
        public static string section_technique_chop {
            get {
                return ResourceManager.GetString("section_technique_chop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        public static string section_technique_counter {
            get {
                return ResourceManager.GetString("section_technique_counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip.
        /// </summary>
        public static string section_technique_flip {
            get {
                return ResourceManager.GetString("section_technique_flip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lob.
        /// </summary>
        public static string section_technique_lob {
            get {
                return ResourceManager.GetString("section_technique_lob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string section_technique_miscellaneous {
            get {
                return ResourceManager.GetString("section_technique_miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string section_technique_na {
            get {
                return ResourceManager.GetString("section_technique_na", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string section_technique_push {
            get {
                return ResourceManager.GetString("section_technique_push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push
        ///(half-long).
        /// </summary>
        public static string section_technique_push_halflong {
            get {
                return ResourceManager.GetString("section_technique_push_halflong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push
        ///(long).
        /// </summary>
        public static string section_technique_push_long {
            get {
                return ResourceManager.GetString("section_technique_push_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push
        ///(short).
        /// </summary>
        public static string section_technique_push_short {
            get {
                return ResourceManager.GetString("section_technique_push_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PushAggressive.
        /// </summary>
        public static string section_technique_pushaggressive {
            get {
                return ResourceManager.GetString("section_technique_pushaggressive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smash.
        /// </summary>
        public static string section_technique_smash {
            get {
                return ResourceManager.GetString("section_technique_smash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string section_technique_special {
            get {
                return ResourceManager.GetString("section_technique_special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topspin.
        /// </summary>
        public static string section_technique_topspin {
            get {
                return ResourceManager.GetString("section_technique_topspin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topspin
        ///(diagonal).
        /// </summary>
        public static string section_technique_topspin_diag {
            get {
                return ResourceManager.GetString("section_technique_topspin_diag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topspin
        ///(Middle).
        /// </summary>
        public static string section_technique_topspin_middle {
            get {
                return ResourceManager.GetString("section_technique_topspin_middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topspin
        ///(parallel).
        /// </summary>
        public static string section_technique_topspin_parallel {
            get {
                return ResourceManager.GetString("section_technique_topspin_parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopspinSpin.
        /// </summary>
        public static string section_technique_topspinspin {
            get {
                return ResourceManager.GetString("section_technique_topspinspin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopspinTempo.
        /// </summary>
        public static string section_technique_topspintempo {
            get {
                return ResourceManager.GetString("section_technique_topspintempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute number of transitions.
        /// </summary>
        public static string section_transitionmatrix_abs_title {
            get {
                return ResourceManager.GetString("section_transitionmatrix_abs_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition probabilities.
        /// </summary>
        public static string section_transitionmatrix_prob_title {
            get {
                return ResourceManager.GetString("section_transitionmatrix_prob_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition matrix.
        /// </summary>
        public static string section_transitionmatrix_title {
            get {
                return ResourceManager.GetString("section_transitionmatrix_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sets.
        /// </summary>
        public static string sets_all {
            get {
                return ResourceManager.GetString("sets_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        public static string sets_multiple {
            get {
                return ResourceManager.GetString("sets_multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string sets_one {
            get {
                return ResourceManager.GetString("sets_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backhand.
        /// </summary>
        public static string side_backhand {
            get {
                return ResourceManager.GetString("side_backhand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BH.
        /// </summary>
        public static string side_backhand_short {
            get {
                return ResourceManager.GetString("side_backhand_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backhand (Steparound).
        /// </summary>
        public static string side_backhand_steparound {
            get {
                return ResourceManager.GetString("side_backhand_steparound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BH (SA).
        /// </summary>
        public static string side_backhand_steparound_short {
            get {
                return ResourceManager.GetString("side_backhand_steparound_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forehand.
        /// </summary>
        public static string side_forehand {
            get {
                return ResourceManager.GetString("side_forehand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FH.
        /// </summary>
        public static string side_forehand_short {
            get {
                return ResourceManager.GetString("side_forehand_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forehand (Steparound).
        /// </summary>
        public static string side_forehand_steparound {
            get {
                return ResourceManager.GetString("side_forehand_steparound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FH (SA).
        /// </summary>
        public static string side_forehand_steparound_short {
            get {
                return ResourceManager.GetString("side_forehand_steparound_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string stat_not_analysed {
            get {
                return ResourceManager.GetString("stat_not_analysed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net/Out.
        /// </summary>
        public static string table_netout_label {
            get {
                return ResourceManager.GetString("table_netout_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blk.
        /// </summary>
        public static string technique_block_short {
            get {
                return ResourceManager.GetString("technique_block_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chp.
        /// </summary>
        public static string technique_chop_short {
            get {
                return ResourceManager.GetString("technique_chop_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cntr.
        /// </summary>
        public static string technique_counter_short {
            get {
                return ResourceManager.GetString("technique_counter_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flp.
        /// </summary>
        public static string technique_flip_short {
            get {
                return ResourceManager.GetString("technique_flip_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string technique_label_short {
            get {
                return ResourceManager.GetString("technique_label_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lb.
        /// </summary>
        public static string technique_lob_short {
            get {
                return ResourceManager.GetString("technique_lob_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string technique_miscellaneous_short {
            get {
                return ResourceManager.GetString("technique_miscellaneous_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendulum.
        /// </summary>
        public static string technique_pendulum {
            get {
                return ResourceManager.GetString("technique_pendulum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psh.
        /// </summary>
        public static string technique_push_short {
            get {
                return ResourceManager.GetString("technique_push_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string technique_reverse {
            get {
                return ResourceManager.GetString("technique_reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sm.
        /// </summary>
        public static string technique_smash_short {
            get {
                return ResourceManager.GetString("technique_smash_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string technique_special {
            get {
                return ResourceManager.GetString("technique_special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spcl.
        /// </summary>
        public static string technique_special_short {
            get {
                return ResourceManager.GetString("technique_special_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomahawk.
        /// </summary>
        public static string technique_tomahawk {
            get {
                return ResourceManager.GetString("technique_tomahawk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TS.
        /// </summary>
        public static string technique_topspin_short {
            get {
                return ResourceManager.GetString("technique_topspin_short", resourceCulture);
            }
        }
    }
}
