//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.Lib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TT.Lib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string dialog_file_in_use_button_cancel {
            get {
                return ResourceManager.GetString("dialog_file_in_use_button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string dialog_file_in_use_button_ok {
            get {
                return ResourceManager.GetString("dialog_file_in_use_button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t overwrite file &apos;{0}&apos; - it is probably open in another program. Retry overwriting?.
        /// </summary>
        public static string dialog_file_in_use_message {
            get {
                return ResourceManager.GetString("dialog_file_in_use_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File in use.
        /// </summary>
        public static string dialog_file_in_use_title {
            get {
                return ResourceManager.GetString("dialog_file_in_use_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to open generated report.
        /// </summary>
        public static string notification_generated_doubleclick {
            get {
                return ResourceManager.GetString("notification_generated_doubleclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report has been generated. Click here to open it..
        /// </summary>
        public static string notification_generated_text {
            get {
                return ResourceManager.GetString("notification_generated_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generation finished!.
        /// </summary>
        public static string notification_generated_title {
            get {
                return ResourceManager.GetString("notification_generated_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Report ....
        /// </summary>
        public static string notification_generating {
            get {
                return ResourceManager.GetString("notification_generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon olive_letter_v_512 {
            get {
                object obj = ResourceManager.GetObject("olive_letter_v_512", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
