//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TT.Viewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backhand:.
        /// </summary>
        public static string legend_backhand_title {
            get {
                return ResourceManager.GetString("legend_backhand_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banana / Flip.
        /// </summary>
        public static string legend_banana_flip_title {
            get {
                return ResourceManager.GetString("legend_banana_flip_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block / Counter.
        /// </summary>
        public static string legend_block_counter_title {
            get {
                return ResourceManager.GetString("legend_block_counter_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chop.
        /// </summary>
        public static string legend_chop_title {
            get {
                return ResourceManager.GetString("legend_chop_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forehand:.
        /// </summary>
        public static string legend_forehand_title {
            get {
                return ResourceManager.GetString("legend_forehand_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercept.
        /// </summary>
        public static string legend_lineexplanation_intercept_title {
            get {
                return ResourceManager.GetString("legend_lineexplanation_intercept_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of contact → Placement.
        /// </summary>
        public static string legend_lineexplanation_poc_pl_title {
            get {
                return ResourceManager.GetString("legend_lineexplanation_poc_pl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lob.
        /// </summary>
        public static string legend_lob_title {
            get {
                return ResourceManager.GetString("legend_lob_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string legend_misc_title {
            get {
                return ResourceManager.GetString("legend_misc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string legend_push_title {
            get {
                return ResourceManager.GetString("legend_push_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service (with spin).
        /// </summary>
        public static string legend_service_with_spin_title {
            get {
                return ResourceManager.GetString("legend_service_with_spin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service (without spin).
        /// </summary>
        public static string legend_service_without_spin_title {
            get {
                return ResourceManager.GetString("legend_service_without_spin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smash.
        /// </summary>
        public static string legend_smash_title {
            get {
                return ResourceManager.GetString("legend_smash_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topspin.
        /// </summary>
        public static string legend_topspin_title {
            get {
                return ResourceManager.GetString("legend_topspin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rally_server {
            get {
                object obj = ResourceManager.GetObject("rally_server", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rally_winner {
            get {
                object obj = ResourceManager.GetObject("rally_winner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string report_settings_cancel {
            get {
                return ResourceManager.GetString("report_settings_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string report_settings_ok {
            get {
                return ResourceManager.GetString("report_settings_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Generate.
        /// </summary>
        public static string report_settings_ok_generate {
            get {
                return ResourceManager.GetString("report_settings_ok_generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string report_settings_playerchoice_both {
            get {
                return ResourceManager.GetString("report_settings_playerchoice_both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string report_settings_playerchoice_title {
            get {
                return ResourceManager.GetString("report_settings_playerchoice_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Settings.
        /// </summary>
        public static string report_settings_title {
            get {
                return ResourceManager.GetString("report_settings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] report_tmp {
            get {
                object obj = ResourceManager.GetObject("report_tmp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitlist.
        /// </summary>
        public static string result_list_tab_title {
            get {
                return ResourceManager.GetString("result_list_tab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string result_list_tab_title_short {
            get {
                return ResourceManager.GetString("result_list_tab_title_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string table_direction_title {
            get {
                return ResourceManager.GetString("table_direction_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercept.
        /// </summary>
        public static string table_intercept_title {
            get {
                return ResourceManager.GetString("table_intercept_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Table.
        /// </summary>
        public static string table_large_tab_title {
            get {
                return ResourceManager.GetString("table_large_tab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string table_large_tab_title_short {
            get {
                return ResourceManager.GetString("table_large_tab_title_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string table_legend_title {
            get {
                return ResourceManager.GetString("table_legend_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net/Out:.
        /// </summary>
        public static string table_netout_label {
            get {
                return ResourceManager.GetString("table_netout_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        public static string table_numbers_title {
            get {
                return ResourceManager.GetString("table_numbers_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rally:.
        /// </summary>
        public static string table_rally_title {
            get {
                return ResourceManager.GetString("table_rally_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rally score:.
        /// </summary>
        public static string table_score_rally_title {
            get {
                return ResourceManager.GetString("table_score_rally_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set score:.
        /// </summary>
        public static string table_score_set_title {
            get {
                return ResourceManager.GetString("table_score_set_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score:.
        /// </summary>
        public static string table_score_title {
            get {
                return ResourceManager.GetString("table_score_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strokes:.
        /// </summary>
        public static string table_show_strokes_title {
            get {
                return ResourceManager.GetString("table_show_strokes_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Tables.
        /// </summary>
        public static string table_small_tab_title {
            get {
                return ResourceManager.GetString("table_small_tab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string table_small_tab_title_short {
            get {
                return ResourceManager.GetString("table_small_tab_title_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin.
        /// </summary>
        public static string table_spin_title {
            get {
                return ResourceManager.GetString("table_spin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke 1.
        /// </summary>
        public static string table_stroke_1_title {
            get {
                return ResourceManager.GetString("table_stroke_1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke 2.
        /// </summary>
        public static string table_stroke_2_title {
            get {
                return ResourceManager.GetString("table_stroke_2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke 3.
        /// </summary>
        public static string table_stroke_3_title {
            get {
                return ResourceManager.GetString("table_stroke_3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke 4.
        /// </summary>
        public static string table_stroke_4_title {
            get {
                return ResourceManager.GetString("table_stroke_4_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point:.
        /// </summary>
        public static string table_tooltip_rally_point {
            get {
                return ResourceManager.GetString("table_tooltip_rally_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string table_tooltip_rally_server {
            get {
                return ResourceManager.GetString("table_tooltip_rally_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rally score.
        /// </summary>
        public static string table_tooltip_score_rally {
            get {
                return ResourceManager.GetString("table_tooltip_score_rally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set score.
        /// </summary>
        public static string table_tooltip_score_set {
            get {
                return ResourceManager.GetString("table_tooltip_score_set", resourceCulture);
            }
        }
    }
}
