//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TT.Viewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backhand:.
        /// </summary>
        public static string legend_backhand_title {
            get {
                return ResourceManager.GetString("legend_backhand_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banana / Flip.
        /// </summary>
        public static string legend_banana_flip_title {
            get {
                return ResourceManager.GetString("legend_banana_flip_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block / Counter.
        /// </summary>
        public static string legend_block_counter_title {
            get {
                return ResourceManager.GetString("legend_block_counter_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chop.
        /// </summary>
        public static string legend_chop_title {
            get {
                return ResourceManager.GetString("legend_chop_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forehand:.
        /// </summary>
        public static string legend_forehand_title {
            get {
                return ResourceManager.GetString("legend_forehand_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercept.
        /// </summary>
        public static string legend_lineexplanation_intercept_title {
            get {
                return ResourceManager.GetString("legend_lineexplanation_intercept_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of contact → Placement.
        /// </summary>
        public static string legend_lineexplanation_poc_pl_title {
            get {
                return ResourceManager.GetString("legend_lineexplanation_poc_pl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lob.
        /// </summary>
        public static string legend_lob_title {
            get {
                return ResourceManager.GetString("legend_lob_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string legend_misc_title {
            get {
                return ResourceManager.GetString("legend_misc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string legend_push_title {
            get {
                return ResourceManager.GetString("legend_push_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service (with spin).
        /// </summary>
        public static string legend_service_with_spin_title {
            get {
                return ResourceManager.GetString("legend_service_with_spin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service (without spin).
        /// </summary>
        public static string legend_service_without_spin_title {
            get {
                return ResourceManager.GetString("legend_service_without_spin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smash.
        /// </summary>
        public static string legend_smash_title {
            get {
                return ResourceManager.GetString("legend_smash_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topspin.
        /// </summary>
        public static string legend_topspin_title {
            get {
                return ResourceManager.GetString("legend_topspin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string table_direction_title {
            get {
                return ResourceManager.GetString("table_direction_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercept.
        /// </summary>
        public static string table_intercept_title {
            get {
                return ResourceManager.GetString("table_intercept_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Table.
        /// </summary>
        public static string table_large_tab_title {
            get {
                return ResourceManager.GetString("table_large_tab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string table_legend_title {
            get {
                return ResourceManager.GetString("table_legend_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        public static string table_numbers_title {
            get {
                return ResourceManager.GetString("table_numbers_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Tables.
        /// </summary>
        public static string table_small_tab_title {
            get {
                return ResourceManager.GetString("table_small_tab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin.
        /// </summary>
        public static string table_spin_title {
            get {
                return ResourceManager.GetString("table_spin_title", resourceCulture);
            }
        }
    }
}
