//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TT.Viewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string affirmative1 {
            get {
                return ResourceManager.GetString("affirmative1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backhand: ähnelt.
        /// </summary>
        public static string legend_backhand_title {
            get {
                return ResourceManager.GetString("legend_backhand_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Banana / Flip ähnelt.
        /// </summary>
        public static string legend_banana_flip_title {
            get {
                return ResourceManager.GetString("legend_banana_flip_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block / Counter ähnelt.
        /// </summary>
        public static string legend_block_counter_title {
            get {
                return ResourceManager.GetString("legend_block_counter_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chop ähnelt.
        /// </summary>
        public static string legend_chop_title {
            get {
                return ResourceManager.GetString("legend_chop_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forehand: ähnelt.
        /// </summary>
        public static string legend_forehand_title {
            get {
                return ResourceManager.GetString("legend_forehand_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intercept ähnelt.
        /// </summary>
        public static string legend_lineexplanation_intercept_title {
            get {
                return ResourceManager.GetString("legend_lineexplanation_intercept_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Point of contact → Placement ähnelt.
        /// </summary>
        public static string legend_lineexplanation_poc_pl_title {
            get {
                return ResourceManager.GetString("legend_lineexplanation_poc_pl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lob ähnelt.
        /// </summary>
        public static string legend_lob_title {
            get {
                return ResourceManager.GetString("legend_lob_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Misc ähnelt.
        /// </summary>
        public static string legend_misc_title {
            get {
                return ResourceManager.GetString("legend_misc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Push ähnelt.
        /// </summary>
        public static string legend_push_title {
            get {
                return ResourceManager.GetString("legend_push_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service (with spin) ähnelt.
        /// </summary>
        public static string legend_service_with_spin_title {
            get {
                return ResourceManager.GetString("legend_service_with_spin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service (without spin) ähnelt.
        /// </summary>
        public static string legend_service_without_spin_title {
            get {
                return ResourceManager.GetString("legend_service_without_spin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smash ähnelt.
        /// </summary>
        public static string legend_smash_title {
            get {
                return ResourceManager.GetString("legend_smash_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Topspin ähnelt.
        /// </summary>
        public static string legend_topspin_title {
            get {
                return ResourceManager.GetString("legend_topspin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player 1 ähnelt.
        /// </summary>
        public static string player_1 {
            get {
                return ResourceManager.GetString("player_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player 2 ähnelt.
        /// </summary>
        public static string player_2 {
            get {
                return ResourceManager.GetString("player_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rally_server {
            get {
                object obj = ResourceManager.GetObject("rally_server", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rally_winner {
            get {
                object obj = ResourceManager.GetObject("rally_winner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string report_settings_cancel {
            get {
                return ResourceManager.GetString("report_settings_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Match dynamics ähnelt.
        /// </summary>
        public static string report_settings_generalchoice_matchdynamics {
            get {
                return ResourceManager.GetString("report_settings_generalchoice_matchdynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rally length ähnelt.
        /// </summary>
        public static string report_settings_generalchoice_rallylength {
            get {
                return ResourceManager.GetString("report_settings_generalchoice_rallylength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Technical efficiency ähnelt.
        /// </summary>
        public static string report_settings_generalchoice_techefficiency {
            get {
                return ResourceManager.GetString("report_settings_generalchoice_techefficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string report_settings_generalchoice_title {
            get {
                return ResourceManager.GetString("report_settings_generalchoice_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transition matrix ähnelt.
        /// </summary>
        public static string report_settings_generalchoice_transitionmatrix {
            get {
                return ResourceManager.GetString("report_settings_generalchoice_transitionmatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No match loaded.
        ///Preview not available. ähnelt.
        /// </summary>
        public static string report_settings_no_match_loaded {
            get {
                return ResourceManager.GetString("report_settings_no_match_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string report_settings_ok {
            get {
                return ResourceManager.GetString("report_settings_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save &amp; Generate ähnelt.
        /// </summary>
        public static string report_settings_ok_generate {
            get {
                return ResourceManager.GetString("report_settings_ok_generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Both ähnelt.
        /// </summary>
        public static string report_settings_playerchoice_both {
            get {
                return ResourceManager.GetString("report_settings_playerchoice_both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player ähnelt.
        /// </summary>
        public static string report_settings_playerchoice_title {
            get {
                return ResourceManager.GetString("report_settings_playerchoice_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        public static string report_settings_setchoice_all {
            get {
                return ResourceManager.GetString("report_settings_setchoice_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crunch ähnelt.
        /// </summary>
        public static string report_settings_setchoice_crunchtime {
            get {
                return ResourceManager.GetString("report_settings_setchoice_crunchtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die +Combi ähnelt.
        /// </summary>
        public static string report_settings_setchoice_pluscombi {
            get {
                return ResourceManager.GetString("report_settings_setchoice_pluscombi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sets ähnelt.
        /// </summary>
        public static string report_settings_setchoice_title {
            get {
                return ResourceManager.GetString("report_settings_setchoice_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4th ähnelt.
        /// </summary>
        public static string report_settings_strokechoice_fourth {
            get {
                return ResourceManager.GetString("report_settings_strokechoice_fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last ähnelt.
        /// </summary>
        public static string report_settings_strokechoice_last {
            get {
                return ResourceManager.GetString("report_settings_strokechoice_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number ähnelt.
        /// </summary>
        public static string report_settings_strokechoice_number {
            get {
                return ResourceManager.GetString("report_settings_strokechoice_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Placement ähnelt.
        /// </summary>
        public static string report_settings_strokechoice_placement {
            get {
                return ResourceManager.GetString("report_settings_strokechoice_placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Return ähnelt.
        /// </summary>
        public static string report_settings_strokechoice_return {
            get {
                return ResourceManager.GetString("report_settings_strokechoice_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service ähnelt.
        /// </summary>
        public static string report_settings_strokechoice_service {
            get {
                return ResourceManager.GetString("report_settings_strokechoice_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Side ähnelt.
        /// </summary>
        public static string report_settings_strokechoice_side {
            get {
                return ResourceManager.GetString("report_settings_strokechoice_side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Step Around ähnelt.
        /// </summary>
        public static string report_settings_strokechoice_steparound {
            get {
                return ResourceManager.GetString("report_settings_strokechoice_steparound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Technique ähnelt.
        /// </summary>
        public static string report_settings_strokechoice_technique {
            get {
                return ResourceManager.GetString("report_settings_strokechoice_technique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3rd ähnelt.
        /// </summary>
        public static string report_settings_strokechoice_third {
            get {
                return ResourceManager.GetString("report_settings_strokechoice_third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strokes ähnelt.
        /// </summary>
        public static string report_settings_strokechoice_title {
            get {
                return ResourceManager.GetString("report_settings_strokechoice_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report Settings ähnelt.
        /// </summary>
        public static string report_settings_title {
            get {
                return ResourceManager.GetString("report_settings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report Settings ähnelt.
        /// </summary>
        public static string report_settings_window_title {
            get {
                return ResourceManager.GetString("report_settings_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hitlist ähnelt.
        /// </summary>
        public static string result_list_tab_title {
            get {
                return ResourceManager.GetString("result_list_tab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die H ähnelt.
        /// </summary>
        public static string result_list_tab_title_short {
            get {
                return ResourceManager.GetString("result_list_tab_title_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistics ähnelt.
        /// </summary>
        public static string statistics {
            get {
                return ResourceManager.GetString("statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Direction ähnelt.
        /// </summary>
        public static string table_direction_title {
            get {
                return ResourceManager.GetString("table_direction_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intercept ähnelt.
        /// </summary>
        public static string table_intercept_title {
            get {
                return ResourceManager.GetString("table_intercept_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Large Table ähnelt.
        /// </summary>
        public static string table_large_tab_title {
            get {
                return ResourceManager.GetString("table_large_tab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die L ähnelt.
        /// </summary>
        public static string table_large_tab_title_short {
            get {
                return ResourceManager.GetString("table_large_tab_title_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legend ähnelt.
        /// </summary>
        public static string table_legend_title {
            get {
                return ResourceManager.GetString("table_legend_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Net/Out: ähnelt.
        /// </summary>
        public static string table_netout_label {
            get {
                return ResourceManager.GetString("table_netout_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Numbers ähnelt.
        /// </summary>
        public static string table_numbers_title {
            get {
                return ResourceManager.GetString("table_numbers_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rally: ähnelt.
        /// </summary>
        public static string table_rally_title {
            get {
                return ResourceManager.GetString("table_rally_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rally score: ähnelt.
        /// </summary>
        public static string table_score_rally_title {
            get {
                return ResourceManager.GetString("table_score_rally_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set score: ähnelt.
        /// </summary>
        public static string table_score_set_title {
            get {
                return ResourceManager.GetString("table_score_set_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score: ähnelt.
        /// </summary>
        public static string table_score_title {
            get {
                return ResourceManager.GetString("table_score_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strokes: ähnelt.
        /// </summary>
        public static string table_show_strokes_title {
            get {
                return ResourceManager.GetString("table_show_strokes_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Small Tables ähnelt.
        /// </summary>
        public static string table_small_tab_title {
            get {
                return ResourceManager.GetString("table_small_tab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S ähnelt.
        /// </summary>
        public static string table_small_tab_title_short {
            get {
                return ResourceManager.GetString("table_small_tab_title_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spin ähnelt.
        /// </summary>
        public static string table_spin_title {
            get {
                return ResourceManager.GetString("table_spin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stroke 1 ähnelt.
        /// </summary>
        public static string table_stroke_1_title {
            get {
                return ResourceManager.GetString("table_stroke_1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stroke 2 ähnelt.
        /// </summary>
        public static string table_stroke_2_title {
            get {
                return ResourceManager.GetString("table_stroke_2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stroke 3 ähnelt.
        /// </summary>
        public static string table_stroke_3_title {
            get {
                return ResourceManager.GetString("table_stroke_3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stroke 4 ähnelt.
        /// </summary>
        public static string table_stroke_4_title {
            get {
                return ResourceManager.GetString("table_stroke_4_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Point: ähnelt.
        /// </summary>
        public static string table_tooltip_rally_point {
            get {
                return ResourceManager.GetString("table_tooltip_rally_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server: ähnelt.
        /// </summary>
        public static string table_tooltip_rally_server {
            get {
                return ResourceManager.GetString("table_tooltip_rally_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rally score ähnelt.
        /// </summary>
        public static string table_tooltip_score_rally {
            get {
                return ResourceManager.GetString("table_tooltip_score_rally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set score ähnelt.
        /// </summary>
        public static string table_tooltip_score_set {
            get {
                return ResourceManager.GetString("table_tooltip_score_set", resourceCulture);
            }
        }
    }
}
